### ISSUE TITLE
Keylogger

### ISSUE THREAD

**Issue by ayashgupta** [000Zer000/ZKit-Framework#5]
I dont know how this keylogger works. 
For other keyloggers, I had to insert the email address and password, however, here it asks for the IP address and port. 

Is it possible to generate an email keylogger?

**Comment by 000Zer000** [comment]
thanks for opening an issue . this keylogger uses a live TCP stream (connection) to send keystroeks . the connetion is reverse so the payload has to know where to connect and from which port  . i think feautre request may work better for this kind of issues . but there is enough reasons to dont do that . think of a senario : "You are in the system . you want to steel the password . a live stream will transfer . you are using zkit controller for accesing the keylogger on victim system **if victim got a problem in network connection . you stil have some part that have been tranfered** so you can run a brute force attack for getting that **part of password that internet connection interupted** . " but that senario with transfer from email : "You are in the system . you want to steel the password .  . you are waiting for an email from  the keylogger on victim system" **if victim got a problem in network connection . the connection gets interepted. the email wont send** . *you dont know when the victim may come online . so you loose the data* .  but you need the password and  run a brute force attack for getting password . because you have no info from the password so brute force cant get you the password  .so the operation is a big loss .  . the diffrence is in first there is **70% chance to get the password and the second nearly %20 .**

**Comment by 000Zer000** [comment]
So if you still want the transfer from email . i will see it as a feature request and will add it .

**Comment by 000Zer000** [comment]
just tell me 

Have Fun !

**Comment by ayashgupta** [comment]
Including the email will be a good option to include besides what you have already done. 
Also, encrypting the code with 2 or 3 options and obfuscating the code will be a great add-on. (Only if it is possible).


It is a great software and has such a great developer. All the best and have fun!

**Comment by 000Zer000** [comment]
> Including the email will be a good option to include besides what you have already done.
> Also, encrypting the code with 2 or 3 options and obfuscating the code will be a great add-on. (Only if it is possible).
> 
> It is a great software and has such a great developer. All the best and have fun!

Thanks for you suggestions . About the encryption of payload (not only in base64.b85) is a very good suggestion . .Im very happy that you liked the software . and very happy of that i have met a nice client . 
Anyway If you need anything any suggestion , or bug . Im always ready for answering . and in the README i have said . if you really like it you can star this porject to give me a "Good job" and watch the project for newer version . 

You too !

**Comment by ayashgupta** [comment]
I have another question for you. Usually, if we bypass the antivirus, the windows shows us another pop-up which asks us to run or don't run the program. This might be because of the digital signature/certificate. Is there any way to fake a digital signature or certificate in the payload?

Also, would you recommend any python script obfuscater? Like, the obfuscating or crypting softwares I found doesn't work on python generated exe of files but works on C generated payloads.

**Comment by 000Zer000** [comment]
It looks like we need this issue opened

**Comment by 000Zer000** [comment]
You have asked 2 questions and Im very pleased to answer them . 

1. it asks for UAC (the pop-up you are talking about) because the payload moves itself to C:\Windows\System32 . and it needs admin access . and is not related to digital signature/certificate . when i download Process explorer from the store in windows 10 and the certificate is for microsoft and still pops up and alerts you so no diffrence .if you are compiling it please use uac-admin for windows when using pyinstaller (for pyexe i dont remember the flag name) . so it asks for the access and everything works just fine. in linux it uses sudo and checks root access . if has deployes the payload to somewhere safe. Im all at service for zkit . i will do resarch and find a way for using it without UAC . but for now i have no way .   

2. It already uses an encryption (base85) . I think encryption with decode stub is enough obfuscation . i know sth about encryption methods like XOR or base64 . but they are very common and usually AVs detect it so i use base85 . (base64.b85encode for encoding and  base64.b85decode for decoding) . at tests that i had base85 was not detected so i found it useful . with random whitespaces and random variable names its less likely two payloads look the same .

And Im working in keylogger that sends keystroeks from email . its under hard tests . if payload gets pass i will add it in next release . and im going to use more ways for encryption of payload . (like chaining some encryptions together) .

Have Fun !

**Comment by ayashgupta** [comment]
For 1, I tried something and I guess it worked. I uploaded the file to a web hosting server, and then I downloaded it with Lime Downloader. It worked afterwards without any conditions however, it only works with C or CS generated payloads.

**Comment by 000Zer000** [comment]
> For 1, I tried something and I guess it worked. I uploaded the file to a web hosting server, and then I downloaded it with Lime Downloader. It worked afterwards without any conditions however, it only works with C or CS generated payloads.

Anyway im really happy you found sth good and im working at sth that may help getting admin access without UAC . its under test so lets hope it gets past and if the results were good enough . i will release a patch . that will the hiddener stub for windows . 

Good job and Have Fun !

**Comment by 000Zer000** [comment]
Im closing this issue . if any future problems occured . please open another one .
