### ISSUE TITLE
zkit.py doesnt open

### ISSUE THREAD

**Issue by torp3do** [000Zer000/ZKit-Framework#8]
**Describe What is going wrong**
app doesnt open

**Expected behavior**
not opening 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: (Specify if it is Linux or Windows)   android 8 samsung s7 rooted
 - Python Version [e.g. 2.7.0, 3.7.1]      pythin 3.8.5
clang version 9.0.8
 - Version Of ZKit-Framework [e.g. 1.2.0]    i cant open it so i dont know what it is, but is just download it now

**Additional context**
![118205857_581670606046535_3926864995903207217n](https://user-images.githubusercontent.com/67332791/90435461-578e0a00-e0cf-11ea-8072-7e39c73ca32b.jpg)

**Comment by 000Zer000** [comment]
Hi thanks for opening this issue + another thanks for using templates . i have commited a bug fix . it might be yours . 

Have Fun !

**Comment by torp3do** [comment]
thanks for your fast action, it works now well.
however it didnt generate payload.
screenshots are follow.
why it asks for payload to windows or linux, i am planning to use it on android device, will the keylogger work or on?
can we change the amount of letters to become around 400 not only 20, otherwise we will get alot of emails.
thank you for ur efforts.
![118053399_1261564967520138_3456506414592054303_n](https://user-images.githubusercontent.com/67332791/90438787-ce79d180-e0d4-11ea-9983-c510d52767f4.jpg)
![118205857_581670606046535_3926864995903207217n](https://user-images.githubusercontent.com/67332791/90438793-d0439500-e0d4-11ea-972d-3d86ff0ef910.jpg)

**Comment by 000Zer000** [comment]
As in screen shots zkit asked about an encryption method and looks like you passed <Enter> to it . so zkit cant understand your choice . please choose one of "1" or "2" (without double qouads)

**Comment by 000Zer000** [comment]
> why it asks for payload to windows or linux, i am planning to use it on android device, will the keylogger work or on?

Im sorry because of hardness of convert python file to an APK. none of these payloads work on android . An android payload is best when written in java . 
But **I HAVE GOOOOOD NEWS** . Not in next release . in next release im adding ruby payloads and for the new release after this newer im adding several java payload and some of them will be for android too

> can we change the amount of letters to become around 400 not only 20, otherwise we will get alot of emails.

Thanks for saying your idea about it . but think of this senario **"After sometimes planing and using diffrent tools you have a generated keylogger by zkit that will record 400 hits then sends it back to attacker . you deploy it , user runs it . the user types his/her password and you are still waiting for the mail . but user gets tired and never writes 400 letters and shutsdown the computer . so you loose the password"**

what a bad luck ! huh ? But if the payload send 20 keystoeks you never loose password

I know it may send lots of email . but do you accept a clean mailbox with cost of loosing keystroeks ??

Anyway Have Fun !

**Comment by 000Zer000** [comment]
If your problem is solved . please consider closing this issue and i will be happy if you star this project

Have Fun !

**Comment by 000Zer000** [comment]
Im closing this issue i hope you got your issue fixed if yes im very happy that i have helped if not just reopen it
